#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom abind abind
#' @importFrom data.table data.table
#' @importFrom data.table fwrite
#' @importFrom data.table rbindlist
#' @importFrom data.table setnames
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 geom_boxplot
#' @importFrom ggplot2 geom_jitter
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 theme_light
#' @importFrom limma duplicateCorrelation
#' @importFrom limma eBayes
#' @importFrom limma lmFit
#' @importFrom methods new
#' @importFrom purrr imap
#' @importFrom purrr iwalk
#' @importFrom purrr keep
#' @importFrom purrr list_flatten
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map_dbl
#' @importFrom purrr map_int
#' @importFrom purrr map_lgl
#' @importFrom purrr map2
#' @importFrom purrr pwalk
#' @importFrom purrr reduce
#' @importFrom purrr set_names
#' @importFrom purrr walk
#' @importFrom reshape2 acast
#' @importFrom stats as.formula
#' @importFrom stats cor
#' @importFrom stats median
#' @importFrom stats p.adjust
#' @importFrom stats p.adjust.methods
#' @importFrom stats sd
#' @importFrom stringr str_c
#' @importFrom stringr str_match
#' @importFrom stringr str_split_i
#' @importFrom utils combn
#' @importFrom utils str
#' @importFrom yaml read_yaml
#' @importFrom yaml write_yaml
## usethis namespace: end
NULL
